def generate_mover_script(
    cache_mount: str, pool_mount: str, age_hours: int, min_free_pct: int
) -> str:
    return f"""#!/bin/bash
# FugginNAS-mover.sh — generated by FugginNAS
CACHE={cache_mount}
POOL={pool_mount}
MIN_FREE_PCT={min_free_pct}
AGE_HOURS={age_hours}

cache_used_pct=$(df --output=pcent "$CACHE" | tail -1 | tr -d ' %')
if [ "$cache_used_pct" -lt $((100 - MIN_FREE_PCT)) ]; then
  exit 0
fi

find "$CACHE" -mindepth 1 -not -path '*/\\.*' \\
  -mmin +$((AGE_HOURS * 60)) -type f | while read -r file; do
  rel="${{file#$CACHE/}}"
  dest="$POOL/$rel"
  mkdir -p "$(dirname "$dest")"
  rsync -ax --remove-source-files "$file" "$dest"
done
"""
