def generate_conf(parity_disks: list[str], data_mounts: list[str], parity_mode: str) -> str:
    lines = ["# Generated by FugginNAS", ""]

    lines.append(f"parity {parity_disks[0]}/snapraid.parity")
    if parity_mode == "dual":
        lines.append(f"2-parity {parity_disks[1]}/snapraid.parity")
    lines.append("")

    lines.append("content /var/snapraid/snapraid.content")
    for mount in data_mounts:
        lines.append(f"content {mount}/snapraid.content")
    lines.append("")

    for i, mount in enumerate(data_mounts, start=1):
        lines.append(f"data d{i} {mount}")
    lines.append("")

    lines += ["exclude *.tmp", "exclude *.!sync", ""]

    return "\n".join(lines)
